import { Link } from "react-router-dom";

const ServiceSpecificTerms = () => {
  return (
    <div
      id="page-container"
      className="max-w-2xl mx-auto px-4 py-14 md:py-20 font-sans text-base text-foreground"
    >
      <h1 className="text-3xl md:text-4xl font-bold mb-8 tracking-tight text-center">
        Service Specific Terms
      </h1>
      <div className="mb-8 text-center">
        <div className="font-semibold text-lg mb-1">MyTechPassport Inc.</div>
        <div className="text-muted-foreground">
          <span className="font-semibold">Posted:</span> May 9, 2025
        </div>
        <div className="text-muted-foreground">
          <span className="font-semibold">Effective as of:</span> May 9, 2025
        </div>
      </div>
      <div className="mb-5">
        Unless otherwise defined in this Service Schedule, capitalized terms
        will have the meaning given to them in the MyTechPassport Terms of
        Service (“Terms”) (currently available at{" "}
        <Link
          to="/terms-of-service/"
          className="text-blue-700 underline hover:text-blue-900 transition"
        >
          /terms-of-service/
        </Link>
        ) and the MyTechPassport Privacy Policy (current available at{" "}
        <Link
          to="/privacy-policy/"
          className="text-blue-700 underline hover:text-blue-900 transition"
        >
          /privacy-policy/
        </Link>
        ).‍
      </div>

      <h2 className="text-2xl font-semibold mt-10 mb-3 tracking-tight">
        MyTechPassport E-sign (END USER AND WEBAPP)‍
      </h2>
      <ul className="list-disc pl-6 mb-8 space-y-3">
        <li>
          <span className="font-semibold">1. &nbsp; Service Description.</span>{" "}
          MyTechPassport E-sign is an electronic signature service which allows
          Customers to display, deliver, acknowledge, store, and electronically
          sign documents.‍
        </li>
        <li>
          <span className="font-semibold">2. &nbsp; Authentication.</span> A
          person signing a document via MyTechPassport E-sign must either have a
          MyTechPassport E-sign account or have received a request for signature
          in their email account.‍
        </li>
        <li>
          <span className="font-semibold">3. &nbsp; Audit Trails.</span>{" "}
          Documents completed in MyTechPassport E-sign include an audit trail
          that contains information that helps track documents through their
          lifecycles. This information includes, but is not limited to, a unique
          document ID generated by MyTechPassport E-sign, email addresses of the
          sender and recipient(s), and IP addresses of the sender and
          recipient(s). The audit trail also includes information, such as date,
          time, and location, about the following events: when a document is
          uploaded, viewed, removed, or sent, when a document is signed or
          declined, when a signer’s email address is updated, when a signer’s
          access code is authenticated, and when a signature request is
          cancelled.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-10 mb-3 tracking-tight">
        MyTechPassport E-sign API‍
      </h2>
      <ul className="list-disc pl-6 mb-8 space-y-3">
        <li>
          <span className="font-semibold">1. &nbsp; Service Description.</span>{" "}
          The MyTechPassport E-sign Application Programming Interface
          (“MyTechPassport E-sign API”) allows Customers to easily integrate or
          embed the MyTechPassport E-sign electronic signature solution into
          their applications or workflows, creating a clean, branded, and
          seamless online experience allowing users to complete agreements or
          transactions.
        </li>
        <li>
          <span className="font-semibold">2. &nbsp; Authentication.</span> To
          the extent that Customer elects to use the MyTechPassport E-sign API
          to enable embedded features on Customer Properties, Customer is
          required to authenticate the identity of each signer/end user through
          email confirmation or such other means that MyTechPassport may approve
          in its sole discretion. Customer is solely responsible and liable for
          such authentication and will indemnify, defend and hold MyTechPassport
          harmless against any claim related to such authentication.‍
        </li>
        <li>
          <span className="font-semibold">3. &nbsp; Signature Requests.</span> A
          “Signature Request” is the transaction that takes place when Customer
          initiates a new signature process and makes a corresponding call to
          the MyTechPassport E-sign APIs. For example, if Customer calls
          “signature_request/send” to send out documents for signature, this
          will constitute one (1) Signature Request. Please note that a single
          Signature Request can be used to gather signatures from multiple
          signers.
        </li>
        <li>
          <span className="font-semibold">4. &nbsp; API Keys.</span> In order to
          use the MyTechPassport E-sign APIs, Customer must obtain its unique
          API credentials (an “API Key”) via the registration process. Customer
          is solely responsible for all activity associated with its API Key,
          regardless of whether it has knowledge of such activity. Customer must
          not share its API Key with any third party, shall keep such API Key
          secure, and shall use it as Customer’s sole means of accessing the
          MyTechPassport E-sign API.‍
        </li>
        <li>
          <span className="font-semibold">5. &nbsp; Transactions.</span>
          <ul className="list-disc pl-6 mt-1 space-y-2">
            <li>
              <span className="font-semibold">a. &nbsp; Limits.</span> Customer
              can make up to 100 requests per minute for standard API requests,
              and 25 requests per minute for higher tier API requests. In test
              mode, Customer can do 10 requests per minute. Collectively the
              above are “Transaction Limits.”
            </li>
            <li>
              <span className="font-semibold">b. &nbsp; Rate Limits.</span>{" "}
              MyTechPassport may be required to limit or suspend Customer’s use
              of the MyTechPassport E-sign API when such suspension or limits
              are necessary to prevent harm or liability to other
              Customers/individuals, or to preserve the security, stability,
              availability or integrity of the MyTechPassport E-sign Services.
            </li>
          </ul>
        </li>
        <li>
          <span className="font-semibold">6. &nbsp; Properties.</span> Only
          those Customer Properties that have been approved by MyTechPassport
          may access and use the MyTechPassport E-sign API. MyTechPassport
          reserves the right to reject any Customer Property, for any reason, in
          its sole discretion, including but not limited to ensure that Customer
          complies with the Terms and the Acceptable Use Policy. Furthermore,
          Customer agrees to ensure that the Customer Properties contain terms
          of service and privacy policies that are consistent with the terms of
          this Agreement.
        </li>
        <li>
          <span className="font-semibold">7. &nbsp; API Restrictions.</span>{" "}
          Customer agrees that it will not (and will not permit any third party
          to) directly or indirectly: (a) create an API client that functions
          substantially the same as the MyTechPassport E-sign APIs; (b) make any
          use of the MyTechPassport E-sign APIs for any purpose independent of
          the Customer Properties; (c) misrepresent the source or ownership of
          the MyTechPassport E-sign APIs or remove, obscure, or alter any
          copyright, trademark or other proprietary rights notices, falsify or
          delete any author attributions, legal notices or other labels of the
          origin or source of the MyTechPassport E-sign APIs; or (d) interfere
          with or disrupt the MyTechPassport E-sign APIs or the servers or
          networks providing the MyTechPassport E-sign APIs or MyTechPassport
          E-sign Services.
        </li>
        <li>
          <span className="font-semibold">
            8. &nbsp; Customer Applications.
          </span>{" "}
          Customer may use the MyTechPassport E-sign APIs to develop
          applications and/or embedded signing experiences for use by Customer
          or Customer’s clients and their respective end users (collectively
          “Customer Applications”). Customer shall be solely responsible for the
          Customer Applications and shall ensure it has: a) provided its
          customers, clients, and end users with the applicable terms (including
          privacy terms) that authorize MyTechPassport to provide the
          MyTechPassport E-sign Services hereunder, and b) the proper authority
          and/or authorization to share user or signer information (including
          personally identifiable information) with MyTechPassport.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-10 mb-3 tracking-tight">
        THIRD PARTY INTEGRATIONS / CONNECTORS‍
      </h2>
      <ul className="list-disc pl-6 mb-8 space-y-3">
        <li>
          <span className="font-semibold">1. &nbsp; Service Description.</span>{" "}
          Third party integrations help connect the MyTechPassport E-sign
          Services with other services like Google (Gmail, Google Docs, Google
          Drive, and G Suite), Evernote, Hubspot CRM, Microsoft OneDrive,
          Dropbox, Oracle, and Slack.
        </li>
        <li>
          <span className="font-semibold">2. &nbsp; Eligibility.</span> Customer
          must be a customer of MyTechPassport E-sign and a customer of the
          service Customer wants to use the integration with. Some integrations
          may require that Customer approve the use of such service and/or
          consent to the transfer of Customer’s information/data between the
          MyTechPassport E-sign Services and the third party service.‍
        </li>
        <li>
          <span className="font-semibold">
            3. &nbsp; Third Party Content and Products.
          </span>{" "}
          Customer is solely responsible for the use of such integration or
          third party service, and ensuring that Customer has the proper rights
          and permissions to share data between the MyTechPassport E-sign
          Services and the third party services. You understand that the third
          party integrations may provide Customer with access to third party
          content and to third party products that may access Customer’s
          instance of the MyTechPassport E-sign Services and export, delete or
          otherwise alter Customer Data (including Customer’s Confidential
          Information).‍
        </li>
        <li>
          <span className="font-semibold">4. &nbsp; Disclaimer.</span>{" "}
          MyTechPassport does not warrant or directly support third party
          integrations, third party content, third party products (whether or
          not these items are designated by MyTechPassport as “powered”,
          “verified” or otherwise) and disclaims all responsibility and
          liability for these items and their access to the MyTechPassport
          E-sign Services, including their modification, deletion, disclosure or
          collection of Customer Data.
        </li>
      </ul>

      <div className="mx-auto mt-12 mb-2 w-full max-w-lg rounded-[15px] bg-muted/20 p-6 text-center font-sans">
        <h3 className="mb-2 mt-4 text-lg font-semibold tracking-tight font-sans">
          MyTechPassport Terms of Service
        </h3>
        <div className="mb-5">
          <Link
            to="/terms-of-service/"
            className="text-blue-700 underline hover:text-blue-900 font-sans"
          >
            View Terms
          </Link>
        </div>
        <h3 className="mb-2 mt-4 text-lg font-semibold tracking-tight font-sans">
          Service Specific Terms
        </h3>
        <div className="mb-5">
          <Link
            to="/service-specific-terms/"
            className="text-blue-700 underline hover:text-blue-900 font-sans"
          >
            View Service Specific Terms
          </Link>
        </div>
        <h3 className="mb-2 mt-4 text-lg font-semibold tracking-tight font-sans">
          Acceptable Use Policy
        </h3>
        <div className="mb-5">
          <Link
            to="/acceptable-use-policy/"
            className="text-blue-700 underline hover:text-blue-900 font-sans"
          >
            View Acceptable Use Policy
          </Link>
        </div>
        <h3 className="mb-2 mt-4 text-lg font-semibold tracking-tight font-sans">
          Data Processing Agreement
        </h3>
        <div className="mb-5">
          <Link
            to="/data-processing-agreement/"
            className="text-blue-700 underline hover:text-blue-900 font-sans"
          >
            View Data Processing Agreement
          </Link>
        </div>
        <h3 className="mb-2 mt-4 text-lg font-semibold tracking-tight font-sans">
          MyTechPassport E-sign Terms of Use
        </h3>
        <div className="mb-5">
          <Link
            to="/electronic-signature/terms/"
            className="text-blue-700 underline hover:text-blue-900 font-sans"
          >
            View Terms
          </Link>
        </div>
        <h3 className="mb-2 mt-4 text-lg font-semibold tracking-tight font-sans">
          MyTechPassport E-sign Legality Statement
        </h3>
        <div>
          <Link
            to="/electronic-signature/legality-statement/"
            className="text-blue-700 underline hover:text-blue-900 font-sans"
          >
            View Legality Statement
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ServiceSpecificTerms;
